### ISSUE TITLE
Fallback for macOS without CoreText: use Unix headers?

### ISSUE THREAD

**Issue by barracuda156** [plfjohnson/devEMF#1]
`devEMF` fails to build on 10.6.8 due to missing CoreText:
```
* installing *source* package ‘devEMF’ ...
** using staged installation
configure: creating ./config.status
config.status: creating src/Makevars
** libs
/opt/local/bin/g++-mp-12 -std=gnu++14 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isystem/opt/local/include/LegacySupport -I/opt/local/include   -fPIC  -pipe -Os -arch ppc  -c devEMF.cpp -o devEMF.o
In file included from devEMF.cpp:48:
fontmetrics.h:64:10: fatal error: CoreText/CTFont.h: No such file or directory
   64 | #include <CoreText/CTFont.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [devEMF.o] Error 1
ERROR: compilation failed for package ‘devEMF’
* removing ‘/opt/local/var/macports/build/_opt_PPCRosettaPorts_R_R-devEMF/R-devEMF/work/devEMF-4.2/devEMF.Rcheck/devEMF’
```

Should generic Unix header be used instead?

**Comment by plfjohnson** [comment]
Good point; rather than using #ifdef to test for R's \_\_APPLE\_\_  define, devEMF should directly test for the presence of CoreText headers and generate its own #define.  That way it could fall back to the generic unix headers.

This change would require modifying configure.ac and src/fontmetrics.h.  If you were to make such changes, I'd be happy to review a pull request.

**Comment by barracuda156** [comment]
@plfjohnson Thank you for responding. For CoreText, it is known to be available from 10.8 onwards: https://developer.apple.com/documentation/coretext
So perhaps we can just use `AvailabilityMacros.h` and `MAC_OS_X_VERSION_MIN_REQUIRED > 1080`? I am not good with autotools to write a check for headers presence, but IMO it is not needed here, Apple systems are predictable.

CoreFoundation headers _are_ present in older macOS versions though (I did not look into Tiger yet, but on 10.6.8 they are present, while CoreText is missing, of course). I do not know if these can work only in couple or not? That is, if we have CoreFoundation set of headers, but no CoreText, should Unix fallback be used, or rather some “hybrid” option?

**Comment by plfjohnson** [comment]
Your solution with `AvailabilityMacros.h` sounds sounds reasonable.  However, the autoconf file will have to be tweaked anyway because it currently handles Darwin systems separately from other Unix (adds the CoreText framework to the link line and doesn't check for zlib, xft, freetype).

The CoreFoundation headers are only used to insofar as required by functions from CoreText (which in turn is only used for font metric support), so no need to have hybrid Apple support.   I don't have easy access to an Apple machine and am generally ignorant about macOS.  For instance, might an Apple machine have zlib, xft or freetype installed?  Does apple use pkg-config?  Should be straightforward to add  fallbacks to whichever of these Unix options are relevant.

**Comment by barracuda156** [comment]
@plfjohnson Yes, sure, all listed dependencies are available for macOS and are supported at least from 10.4.
(They are also widely used in Macports.)

So the only question is how to implement macOS version check in existing build system, and then use generic Unix fallback for everything below the threshold.

Linking should work with no issues, and a number of R packages employ pkgconfig to find libs. It works fine on older macOS.

**Comment by plfjohnson** [comment]
@barracuda156 I just committed a change that (I think) addresses this issue.  Please test the main branch, ideally both on an older macOS system (without CoreText) as well as a newer macOS system (with CoreText), and let me know whether this works.  I do not currently have access to a Apple computer with developer tools, and I do not want to upload to cran until it is tested.

**Comment by barracuda156** [comment]
> @barracuda156 I just committed a change that (I think) addresses this issue.  Please test the main branch, ideally both on an older macOS system (without CoreText) as well as a newer macOS system (with CoreText), and let me know whether this works.  I do not currently have access to a Apple computer with developer tools, and I do not want to upload to cran until it is tested.

Thank you very much! I will try and let you know shortly.

**Comment by barracuda156** [comment]
@plfjohnson I probably need to pass something to configure and I missed that?
```
## ----------- ##
## Core tests. ##
## ----------- ##

configure:2146: checking for pkg-config
configure:2170: found /opt/local/bin/pkg-config
configure:2182: result: /opt/local/bin/pkg-config
configure:2193: checking whether pkg-config knows about xft
configure:2196: result: yes
configure:2200: XFT_CFLAGS=-I/opt/local/include/freetype2 -I/opt/local/include/libpng16
configure:2202: XFT_LIBS=-L/opt/local/lib -lXft
configure:2214: checking whether pkg-config knows about zlib
configure:2217: result: yes
configure:2221: ZLIB_CFLAGS=
configure:2223: ZLIB_LIBS=-L/opt/local/lib -lz
configure:2368: checking for C++ compiler version
configure:2377: /opt/local/bin/g++-mp-12 -std=gnu++14 --version >&5
g++-mp-12 (MacPorts gcc12 12.2.0_0) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:2388: $? = 0
configure:2377: /opt/local/bin/g++-mp-12 -std=gnu++14 -v >&5
Using built-in specs.
COLLECT_GCC=/opt/local/bin/g++-mp-12
COLLECT_LTO_WRAPPER=/opt/local/libexec/gcc/powerpc-apple-darwin10/12.2.0/lto-wrapper
Target: powerpc-apple-darwin10
Configured with: /opt/local/var/macports/build/_opt_PPCRosettaPorts_lang_gcc12/gcc12/work/gcc-12.2.0/configure --prefix=/opt/local --build=powerpc-apple-darwin10 --enable-languages=c,c++,objc,obj-c++,lto,fortran,jit --libdir=/opt/local/lib/gcc12 --includedir=/opt/local/include/gcc12 --infodir=/opt/local/share/info --mandir=/opt/local/share/man --datarootdir=/opt/local/share/gcc-12 --with-local-prefix=/opt/local --with-system-zlib --disable-nls --program-suffix=-mp-12 --with-gxx-include-dir=/opt/local/include/gcc12/c++/ --with-gmp=/opt/local --with-mpfr=/opt/local --with-mpc=/opt/local --with-isl=/opt/local --with-zstd=/opt/local --enable-checking=release --disable-multilib --enable-lto --enable-libstdcxx-time --without-build-config --with-as=/opt/local/bin/as --with-ld=/opt/local/bin/ld --with-ar=/opt/local/bin/ar --with-bugurl=https://trac.macports.org/newticket --enable-host-shared --with-darwin-extra-rpath=/opt/local/lib/libgcc --with-libiconv-prefix=/opt/local --with-tune-cpu=G4 --disable-tls --with-pkgversion='MacPorts gcc12 12.2.0_0'
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (MacPorts gcc12 12.2.0_0) 
configure:2388: $? = 0
configure:2377: /opt/local/bin/g++-mp-12 -std=gnu++14 -V >&5
g++-mp-12: error: unrecognized command-line option '-V'
g++-mp-12: fatal error: no input files
compilation terminated.
configure:2388: $? = 1
configure:2377: /opt/local/bin/g++-mp-12 -std=gnu++14 -qversion >&5
g++-mp-12: error: unrecognized command-line option '-qversion'; did you mean '--version'?
g++-mp-12: fatal error: no input files
compilation terminated.
configure:2388: $? = 1
configure:2408: checking whether the C++ compiler works
configure:2430: /opt/local/bin/g++-mp-12 -std=gnu++14 -pipe -Os -arch ppc -I/opt/local/include/freetype2 -I/opt/local/include/libpng16   conftest.cpp -L/opt/local/lib -lXft -L/opt/local/lib -lz -framework CoreText >&5
ld: framework not found CoreText
collect2: error: ld returned 1 exit status
configure:2434: $? = 1
configure:2474: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "devEMF"
| #define PACKAGE_TARNAME "devemf"
| #define PACKAGE_VERSION "2"
| #define PACKAGE_STRING "devEMF 2"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main (void)
| {
| 
|   ;
|   return 0;
| }
configure:2479: error: in `/opt/local/var/macports/build/_opt_PPCRosettaPorts_R_R-devEMF/R-devEMF/work/devEMF-1a359f2a4c8abe4bb51584da90b8bba8c42d262b':
configure:2481: error: C++ compiler cannot create executables
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_set=set
ac_cv_env_CXX_value=/opt/local/bin/g++-mp-12
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_path_PKGCONF=/opt/local/bin/pkg-config

## ----------------- ##
## Output variables. ##
## ----------------- ##

CPPFLAGS='-I/opt/local/include/freetype2 -I/opt/local/include/libpng16 '
CXX='/opt/local/bin/g++-mp-12 -std=gnu++14'
CXXFLAGS='-pipe -Os -arch ppc'
DEFS=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EXEEXT=''
LDFLAGS=''
LIBOBJS=''
LIBS='-L/opt/local/lib -lXft -L/opt/local/lib -lz -framework CoreText'
LTLIBOBJS=''
OBJEXT=''
PACKAGE_BUGREPORT=''
PACKAGE_NAME='devEMF'
PACKAGE_STRING='devEMF 2'
PACKAGE_TARNAME='devemf'
PACKAGE_URL=''
PACKAGE_VERSION='2'
PATH_SEPARATOR=':'
PKGCONF='/opt/local/bin/pkg-config'
R_HOME='/opt/local/Library/Frameworks/R.framework/Resources'
SHELL='/bin/sh'
ac_ct_CXX=''
bindir='${exec_prefix}/bin'
build_alias=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host_alias=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
runstatedir='${localstatedir}/run'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "devEMF"
#define PACKAGE_TARNAME "devemf"
#define PACKAGE_VERSION "2"
#define PACKAGE_STRING "devEMF 2"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""

configure: exit 77
```

**Comment by plfjohnson** [comment]
@barracuda156  thanks for testing.  I believe the problem was that I was including the "-framework CoreText" option during linking on OSX regardless of whether it existed (or was needed -- the checks were there so that CoreText functions weren't being called if they didn't exist, but the framework was still being requested during linking).  I have pushed a potential fix; please test again when you have a chance.

**Comment by barracuda156** [comment]
@plfjohnson Thank you, I will try again.

**Comment by barracuda156** [comment]
@plfjohnson Awesome, thank you! It works now.

```
config.status: creating src/Makevars
** libs
/opt/local/bin/g++-mp-12 -std=gnu++14 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/opt/local/include/freetype2 -I/opt/local/include/libpng16  -DHAVE_ZLIB -DHAVE_XFT  -isystem/opt/local/include/LegacySupport -I/opt/local/include   -fPIC  -pipe -Os -arch ppc  -c devEMF.cpp -o devEMF.o
/opt/local/bin/g++-mp-12 -std=gnu++14 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/local/Library/Frameworks/R.framework/Resources/lib -Wl,-headerpad_max_install_names -Wl,-rpath,/opt/local/lib/libgcc -L/opt/local/lib -lMacportsLegacySupport -arch ppc -o devEMF.so devEMF.o -L/opt/local/lib -lXft -L/opt/local/lib -lz -F/opt/local/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-devEMF/R-devEMF/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/library/00LOCK-devEMF-69722192912634000e860f25225d7edea2267885/00new/devEMF/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (devEMF)
```
